apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
 
  annotations:
    flowsource/github-repo-owner : mangesh687
    flowsource/github-repo-name : backstage1
    flowsource/jenkins-pipelines : ticket-booking-application
    flowsource/durationInDays : '180'
    cognizant/checkmarx-project-id : backstage
    cognizant/sonarqube-project-key : backstage
    backstage.io/techdocs-ref: dir:.
    backstage/jira-project-key : IPR
    flowsource/github-workflows : 'backstage build &deploy'
    lighthouse.com/website-url: https://backstage.io
spec:
  type: service
  owner: user.gust
  lifecycle: experimental
